### ISSUE TITLE
Link to Firefox addon shows 404 error

### ISSUE THREAD

**Issue by Simon-Tesla** [rotemdan/MaximizerForYouTube#3]
The link in the readme (https://addons.mozilla.org/en-US/firefox/addon/maximizer-for-youtube/) doesn't seem to work anymore.

**Comment by rotemdan** [comment]
The addon used to be available but the AMO reviewers made it hidden from the store's search engine because it bundles jQuery in minified form (their policy is not to allow minified code within a WebExtension). Now it seems like they disabled access to it (probably a general change in policy).

I tried to maintain a single codebase that works both as a WebExtension and userscript. Seems like this is not easily possible. I don't quite have the time to fix this at the moment but I will try. Meanwhile it is possible to install it as a Greasemonkey/Tampermonkey userscript.

**Comment by rotemdan** [comment]
Along with fixing recent issues, I've rearranged and unminified the dependencies and submitted a new version to AMO, which so far has been approved and should be publicly available.
