### ISSUE TITLE
When 2 videos are opened only the last one is playing

### ISSUE THREAD

**Issue by steinex** [rotemdan/MaximizerForYouTube#5]
As the title says. When the extension is active and one opens 2 videos, only the last opened is playing, the first stalls.

This happens with both the userscript or the extension.

**Comment by rotemdan** [comment]
Yes, that's one of intended the behaviors of the script - having only one video playing at a time.
It used to be more important. Now Firefox has its own autopause feature so the need has reduced a bit.

I can understand it may not seem desirable to everyone in every situation. However, the extension doesn't have configuration options (yet). That's one of the reasons it's marked as 'Experimental' in AMO and generally kept in a 'low profile'. I wish I could devote time for this but I really can't at the moment.

**Comment by steinex** [comment]
Hi and thanks for your reply. I digged a bit in the userscript and realized it is intented beharviour.

I will just workaround it by commenting `pauseWhenAnotherPlayerStartsPlaying();`. This is fine for me, so I'll close.

Thank you for this great extension!

**Comment by rotemdan** [comment]
Yes, I tried to organize the code so it's easy to comment out individual features (at least for those who can understand it). In any case, if customization options are introduced in the future, they would, most likely, only be available in the webextension version, since userscripts only act as content scripts - they can't integrate with the browser UI (originally this was developed as a simple userscript).
