### ISSUE TITLE
Should allow autoplay for the current tab

### ISSUE THREAD

**Issue by bedax** [rotemdan/MaximizerForYouTube#6]
Hello, excellent work with this plugin, I really like that it stops autoplay for videos opened in a new (background) tab. However, if I click on a youtube video for the current tab, I usually want it to autoplay, so I think this should be the default behaviour.

**Comment by rotemdan** [comment]
Autoplay has always started for current tab. I'm not sure but the behavior you're describing may be due to a recent change/issue in YouTube itself (video occasionally loads as paused, similarly to an embedded video, with the "play" icon in the middle). If that is the case than I believe it is a recent bug introduced by YouTube. Otherwise I would be interested to know what browser are you using and in what circumstances this happens?

**Comment by bedax** [comment]
Ah my apologies, it didn't occur to until you asked, but I have quite an odd firefox configuration, with things set in user.js and other extensions. I just tried it in a basically vanilla version of firefox and it works fine. I'll try and narrow it down and I'll post here if I find it, but otherwise I doubt it's a fault with this extension so I'll close this now.

Many thanks
